version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${AGE_ATENDE_DATABASE}
      POSTGRES_USER: ${AGE_ATENDE_DATABASE_USER}
      POSTGRES_PASSWORD: ${AGE_ATENDE_DATABASE_PASSWORD}

  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/rails
      - ./config/master.key:/rails/config/master.key
      - ./config/credentials/production.key:/rails/config/credentials/production.key
    working_dir: /rails

volumes:
  postgres_data:
