# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: age_atende_user
  password: <%= ENV['AGE_ATENDE_DATABASE_PASSWORD'] %>
  host: localhost

voalle_db:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 206.204.248.86
  username: <%= ENV['AGE_VOALLE_DATABASE_USER'] %>
  password: <%= ENV['AGE_VOALLE_DATABASE_PASSWORD'] %>
  database: dbemp00489


development:
  <<: *default
  database: age_atende_back_development

test:
  <<: *default
  database: age_atende_back_test

production:
  <<: *default
  database: age_atende_back_production
  username: age_atende_production_user
  password: <%= ENV['AGE_ATENDE_DATABASE_PRODUCTION_PASSWORD'] %>
  host: production_database_host
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
