# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['AGE_ATENDE_DATABASE_USER'] %>
  password: <%= ENV['AGE_ATENDE_DATABASE_PASSWORD'] %>
  host: localhost

voalle_db:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 206.204.248.86
  username: <%= ENV['AGE_VOALLE_DATABASE_USER'] %>
  password: <%= ENV['AGE_VOALLE_DATABASE_PASSWORD'] %>
  database: dbemp00489

native_db:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 10.25.3.171
  username: <%= ENV['AGE_NATIVE_DATABASE_USER'] %>
  password: <%= ENV['AGE_NATIVE_DATABASE_PASSWORD'] %>
  database: db_monitoramento

# sinapse_db:
#   adapter: firebird
#   encoding: utf8
#   port: 3050
#   host: 187.33.31.182
#   database: E:\BD\AGE\SINAPSE.FDB
#   username: <%= ENV['AGE_SINAPSE_DATABASE_USER'] %>
#   password: <%= ENV['AGE_SINAPSE_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: age_atende_back_development

test:
  <<: *default
  database: age_atende_back_test

production:
  <<: *default
  database: <%= ENV['AGE_ATENDE_DATABASE'] %>
  username: <%= ENV['AGE_ATENDE_DATABASE_USER'] %>
  password: <%= ENV['AGE_ATENDE_DATABASE_PASSWORD'] %>
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
